spring.config.import: secrets.yml

spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/first_api_db
#    username: app
#    password: ${db-password}
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: create
  ai:
    openai:
      api-key: ${openai-api-key}

vectorstore:
  qdrant:
    host: localhost
    port: 6334
    collection-name: user-information