apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-api-deployment
  labels:
    app: first-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-api
  template:
    metadata:
      labels:
        app: first-api
    spec:
      containers:
        - name: first-api
          image: dc2software/first-docker-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: openai-api-key
              valueFrom:
                secretKeyRef:
                  key: openai-api-key
                  name: first-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: first-api-service
spec:
  selector:
    app: first-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---