apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-api-deployment
  labels:
    app: first-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-api
  template:
    metadata:
      labels:
        app: first-api
    spec:
      containers:
        - name: first-api
          image: dc2software/first-docker-repo:1.1.3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE
              value: cloud
            - name: openai-api-key
              valueFrom:
                secretKeyRef:
                  key: openai-api-key
                  name: first-api-secret
            - name: serp-api-key
              valueFrom:
                secretKeyRef:
                  key: serp-api-key
                  name: first-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: first-api-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "5749f67f-e391-4cfc-9319-289c78c02b60"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "danielchemicz.com"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "false"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app: first-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer
---