apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6334
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  labels:
    app: qdrant
spec:
  type: NodePort
  ports:
    - port: 6334
      targetPort: 6334
      protocol: TCP
  selector:
    app: qdrant